export const TOKEN = "2832060083511970";
export const BASE_URL = `https://superheroapi.com/api.php/${TOKEN}/`;

export const CHARACTER_LOADING = "CHARACTER_LOADING";
export const CHARACTER_DETAILS_DATA = "CHARACTER_DETAILS_DATA";
export const CHARACTER_DETAIL_INITIAL_STATE = "CHARACTER_DETAIL_INITIAL_STATE";
export const CHARACTER_DETAIL_DATA_ERROR = "CHARACTER_DETAIL_DATA_ERROR";

// Chracter list loading
export const CHARACTERLIST_LOADING = "CHARACTERLIST_LOADING";
export const CHARACTERLIST_DETAILS_DATA = "CHARACTERLIST_DETAILS_DATA";
export const CHARACTERLIST_DETAIL_INITIAL_STATE = "CHARACTERLIST_DETAIL_INITIAL_STATE";
export const CHARACTERLIST_DETAIL_DATA_ERROR = "CHARACTERLIST_DETAIL_DATA_ERROR";

// fetch Hero info
export const HERO_INITIAL_STATE = 'HERO_INITIAL_STATE';
export const HERO_DATA = 'HERO_DATA';
export const HERO_DATA_ERROR = 'HERO_DATA_ERROR';
export const HERO_DATA_LOADING = 'HERO_DATA_LOADING';

// fetch Hero Image
export const HERO_IMAGE_INITIAL_STATE = 'HERO_IMAGE_INITIAL_STATE';
export const HERO_IMAGE_DATA = 'HERO_IMAGE_DATA';
export const HERO_IMAGE_DATA_ERROR = 'HERO_IMAGE_DATA_ERROR';
export const HERO_IMAGE_DATA_LOADING = 'HERO_IMAGE_DATA_LOADING';

// fetch Hero Power
export const HERO_POWER_INITIAL_STATE = 'HERO_POWER_INITIAL_STATE';
export const HERO_POWER_DATA = 'HERO_POWER_DATA';
export const HERO_POWER_DATA_ERROR = 'HERO_POWER_DATA_ERROR';
export const HERO_POWER_DATA_LOADING = 'HERO_POWER_DATA_LOADING';

// fetch Appearance Power
export const HERO_APPEARANCE_INITIAL_STATE = 'HERO_APPEARANCE_INITIAL_STATE';
export const HERO_APPEARANCE_DATA = 'HERO_APPEARANCE_DATA';
export const HERO_APPEARANCE_DATA_ERROR = 'HERO_APPEARANCE_DATA_ERROR';
export const HERO_APPEARANCE_DATA_LOADING = 'HERO_APPEARANCE_DATA_LOADING';

// fetch Biography Power
export const HERO_BIOGRAPHY_INITIAL_STATE = 'HERO_BIOGRAPHY_INITIAL_STATE';
export const HERO_BIOGRAPHY_DATA = 'HERO_BIOGRAPHY_DATA';
export const HERO_BIOGRAPHY_DATA_ERROR = 'HERO_BIOGRAPHY_DATA_ERROR';
export const HERO_BIOGRAPHY_DATA_LOADING = 'HERO_BIOGRAPHY_DATA_LOADING';

// fetch Connection Power
export const HERO_CONNECTION_INITIAL_STATE = 'HERO_CONNECTION_INITIAL_STATE';
export const HERO_CONNECTION_DATA = 'HERO_CONNECTION_DATA';
export const HERO_CONNECTION_DATA_ERROR = 'HERO_CONNECTION_DATA_ERROR';
export const HERO_CONNECTION_DATA_LOADING = 'HERO_CONNECTION_DATA_LOADING';

// fetch Work Power
export const HERO_WORK_INITIAL_STATE = 'HERO_WORK_INITIAL_STATE';
export const HERO_WORK_DATA = 'HERO_WORK_DATA';
export const HERO_WORK_DATA_ERROR = 'HERO_WORK_DATA_ERROR';
export const HERO_WORK_DATA_LOADING = 'HERO_WORK_DATA_LOADING';


// fetch search heros
export const HERO_SEARCH_INITIAL_STATE = 'HERO_SEARCH_INITIAL_STATE';
export const HERO_SEARCH_DATA = 'HERO_SEARCH_DATA';
export const HERO_SEARCH_DATA_ERROR = 'HERO_SEARCH_DATA_ERROR';
export const HERO_SEARCH_DATA_LOADING = 'HERO_SEARCH_DATA_LOADING';

